### ISSUE TITLE
run_requires throws a TypeError on setup files which have no associated extras

### ISSUE THREAD

**Issue by techalchemy** [sarugaku/requirementslib#122]
```console
Traceback (most recent call last):
  File "/home/hawk/git/pipenv/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/hawk/git/pipenv/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/hawk/git/pipenv/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/hawk/git/pipenv/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/hawk/git/pipenv/pipenv/utils.py", line 707, in resolve_deps
    req_dir=req_dir,
  File "/home/hawk/git/pipenv/pipenv/utils.py", line 475, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources,
  File "/home/hawk/git/pipenv/pipenv/utils.py", line 237, in get_resolver_metadata
    req = Requirement.from_line(dep)
  File "/home/hawk/git/pipenv/pipenv/vendor/requirementslib/models/requirements.py", line 1092, in from_line
    r = FileRequirement.from_line(line_with_prefix, extras=extras)
  File "/home/hawk/git/pipenv/pipenv/vendor/requirementslib/models/requirements.py", line 548, in from_line
    return cls.create(**arg_dict)
  File "/home/hawk/git/pipenv/pipenv/vendor/requirementslib/models/requirements.py", line 477, in create
    setup_info = SetupInfo.from_ireq(ireq)
  File "/home/hawk/git/pipenv/pipenv/vendor/requirementslib/models/setup_info.py", line 431, in from_ireq
    created.get_info()
  File "/home/hawk/git/pipenv/pipenv/vendor/requirementslib/models/setup_info.py", line 349, in get_info
    self.get_egg_metadata()
  File "/home/hawk/git/pipenv/pipenv/vendor/requirementslib/models/setup_info.py", line 325, in get_egg_metadata
    extras = ensure_reqs(extras)
  File "/home/hawk/git/pipenv/pipenv/vendor/requirementslib/models/setup_info.py", line 74, in ensure_reqs
    for req in reqs:
TypeError: 'NoneType' object is not iterable
```

**Comment by techalchemy** [comment]
ref: pypa/pipenv#3283
