### ISSUE TITLE
AttributeError: 'AnnAssign' object has no attribute 'targets'

### ISSUE THREAD

**Issue by jacksmith15** [sarugaku/requirementslib#307]
If a `setup.py` contains multiple annotation-assignment statements, it is likely that the following error is raised when it is parsed:

```
AttributeError: 'AnnAssign' object has no attribute 'targets'
```

This is because the logic found [here](https://github.com/sarugaku/requirementslib/blob/330ad38e3ebe1fab99209aaa6373c5652b2b869e/src/requirementslib/models/setup_info.py#L496-L504) does not correctly handle the two cases of `Assign` vs `AnnAssign`.

If an `AnnAssign` is encountered, but it does not assign to the name being retrieved, this logic treats it as an `Assign` by iterating the `targets` attribute, which does not exist.

Because of early return, this occurs exactly when the `AnnAssign` being resolved is not the first one in the AST.

## Steps to reproduce

Take the following `setup.py`:

```python
from typing import List

from setuptools import find_packages, setup

NAME: str = "foo"

REQUIREMENTS: List[str] = ["requests"]

setup(
    name=NAME,
    description="foo",
    long_description="foo",
    version="0.0.1",
    author="me",
    package_dir="foo",
    packages=find_packages(where=".", include=["foo"]),
    python_requires=">=3.9.*",
    install_requires=REQUIREMENTS,
    zip_safe=False,
    classifiers=[
        "Programming Language :: Python :: 3.9",
    ],
)
```

And run the following:

```python
from pathlib import Path

from requirementslib.models.setup_info import SetupReader

print(
    SetupReader.read_setup_py(
        Path("setup.py"),
        raising=False,
    )
)
```

### Expected output

```
{'name': 'foo', 'version': '0.0.1', 'install_requires': ['requests'], 'extras_require': {}, 'python_requires': '>=3.9.*'}
```

### Actual output

```
Traceback (most recent call last):
  File "/path/to/reproduce.py", line 6, in <module>
    SetupReader.read_setup_py(
  File "/path/to/.venv/lib/python3.9/site-packages/requirementslib/models/setup_info.py", line 205, in read_setup_py
    "install_requires": caller(cls._find_install_requires, setup_call, body),
  File "/path/to/.venv/lib/python3.9/site-packages/requirementslib/models/setup_info.py", line 170, in suppress_unparsable
    return func(*args, **kwargs)
  File "/path/to/.venv/lib/python3.9/site-packages/requirementslib/models/setup_info.py", line 362, in _find_install_requires
    variable = cls._find_variable_in_body(body, value.id)
  File "/path/to/.venv/lib/python3.9/site-packages/requirementslib/models/setup_info.py", line 499, in _find_variable_in_body
    for target in elem.targets:
AttributeError: 'AnnAssign' object has no attribute 'targets'
```

**Comment by jacksmith15** [comment]
I expect this can be solved by modifying the method in question like so:

```python
    @staticmethod
    def _find_variable_in_body(body: "Iterable[Any]", name: str) -> "Optional[Any]":
        for elem in body:

            if not isinstance(elem, (ast.Assign, ast.AnnAssign)):
                continue

            if isinstance(elem, ast.Assign):
                for target in elem.targets:
                    if not isinstance(target, ast.Name):
                        continue
                    if target.id == name:
                        return elem.value
            if isinstance(elem, ast.AnnAssign):
                if not elem.value: # Annotation without assignment!
                    continue
                if elem.target.id == name:
                    return elem.value
        return None
```

This also improves handling for annotation without assignment, i.e.

```python
INSTALL_REQUIRES: List[str]
INSTALL_REQUIRES = ["dep1"]
```

I'll try to add a test and open a PR if I find time.

**Comment by jacksmith15** [comment]
I believe it represents an annotated assignment, e.g.

```python
foo: str = "bar"
```

**Comment by Callek** [comment]
@matteius fwiw I just hit this in pipenv today.  Thank you for your efforts!

**Comment by matteius** [comment]
@Callek Can you provide any additional details on the issue you ran into with regards to pipenv?   I was just commenting on the issue, I have no idea what the fix is as I haven't experienced this.

**Comment by Callek** [comment]
> @Callek Can you provide any additional details on the issue you ran into with regards to pipenv? I was just commenting on the issue, I have no idea what the fix is as I haven't experienced this.

I've seen you update the pin for this package in pipenv is why I raised it directly. 

But roughly speaking a package I was working in (proprietary code, under nda) had set variables in setup.py like:
`foo: List[str] = []`

Which if I removed the type annotations from the setup.py the package installed just fine with `oipenv sync`

If it helps you solve this bug I'm happy to work up a minimal steps to reproduce (for pipenv) in a public reproducing repo.

**Comment by Callek** [comment]
I can reproduce by this repo: https://github.com/Callek/foobar-example

If you checkout to the initial commit `pipenv sync` works fine, but if you switch to the HEAD of `main` it does not.
